// Generated by https://quicktype.io

export interface ILocation {
	locations: ILocationElement[];
	warnings: any[];
}

export interface ILocationElement {
	referencePosition: IPosition;
	roadAccessPosition: IPosition;
	address: IAddress;
	formattedAddress: string;
	locationType: string;
	quality: IQuality;
}

export interface IAddress {
	countryName: string;
	state: string;
	province: string;
	postalCode: string;
	city: string;
	district: string;
	subdistrict: string;
	street: string;
	houseNumber: string;
}

export interface IQuality {
	distance: number;
}

export interface IPosition {
	latitude: number;
	longitude: number;
}
