// Generated by https://quicktype.io

export interface Location {
	locations: LocationElement[];
	warnings: any[];
}

export interface LocationElement {
	referencePosition: Position;
	roadAccessPosition: Position;
	address: Address;
	formattedAddress: string;
	locationType: string;
	quality: Quality;
}

export interface Address {
	countryName: string;
	state: string;
	province: string;
	postalCode: string;
	city: string;
	district: string;
	subdistrict: string;
	street: string;
	houseNumber: string;
}

export interface Quality {
	distance: number;
}

export interface Position {
	latitude: number;
	longitude: number;
}
