export type TWeatherCode = [{ [key: string]: string }];

const weatherCodes: TWeatherCode = [
	{
		'0': 'Clear',
		'1': 'Partly cloudy',
		'2': 'Cloudy',
		'3': 'Light rain',
		'4': 'Moderate rain',
		'5': 'Heavy rain',
		'6': 'Thunderstorm',
		'7': 'Light snow',
		'8': 'Moderate snow',
		'9': 'Heavy snow',
		'10': 'Fog',
		'11': 'Light rain and snow',
		'12': 'Moderate rain and snow',
		'13': 'Heavy rain and snow',
		'14': 'Light sleet',
		'15': 'Moderate sleet',
		'16': 'Heavy sleet',
		'17': 'Light drizzle',
		'18': 'Moderate drizzle',
		'19': 'Heavy drizzle',
		'20': 'Light hail',
		'21': 'Moderate hail',
		'22': 'Heavy hail',
		'23': 'Light ice pellets',
		'24': 'Moderate ice pellets',
		'25': 'Heavy ice pellets',
		'26': 'Light thunderstorm',
		'27': 'Moderate thunderstorm',
		'28': 'Heavy thunderstorm',
		'29': 'Light thunderstorm and rain',
		'30': 'Moderate thunderstorm and rain',
		'31': 'Heavy thunderstorm and rain',
		'32': 'Light thunderstorm and snow',
		'33': 'Moderate thunderstorm and snow',
		'34': 'Heavy thunderstorm and snow',
		'35': 'Light thunderstorm and sleet',
		'36': 'Moderate thunderstorm and sleet',
		'37': 'Heavy thunderstorm and sleet',
		'38': 'Light thunderstorm and ice pellets',
		'39': 'Moderate thunderstorm and ice pellets',
		'40': 'Heavy thunderstorm and ice pellets',
		'41': 'Light thunderstorm with hail',
		'42': 'Moderate thunderstorm with hail',
		'43': 'Heavy thunderstorm with hail',
		'44': 'Light thunderstorm with small hail',
		'45': 'Moderate thunderstorm with small hail',
		'46': 'Heavy thunderstorm with small hail',
		'47': 'Light thunderstorm with rain',
		'48': 'Moderate thunderstorm with rain',
		'49': 'Heavy thunderstorm with rain',
		'50': 'Light thunderstorm with snow',
		'51': 'Moderate thunderstorm with snow',
		'52': 'Heavy thunderstorm with snow',
		'53': 'Light thunderstorm with sleet',
		'54': 'Moderate thunderstorm with sleet',
		'55': 'Heavy thunderstorm with sleet',
		'56': 'Light thunderstorm with ice pellets',
		'57': 'Moderate thunderstorm with ice pellets',
		'58': 'Heavy thunderstorm with ice pellets',
		'59': 'Light thunderstorm with hail',
		'60': 'Moderate thunderstorm with hail',
		'61': 'Heavy thunderstorm with hail',
		'62': 'Light thunderstorm with small hail',
		'63': 'Moderate thunderstorm with small hail',
		'64': 'Heavy thunderstorm with small hail',
		'65': 'Light rain and snow',
		'66': 'Moderate rain and snow',
		'67': 'Heavy rain and snow',
		'68': 'Light rain and sleet',
		'69': 'Moderate rain and sleet',
		'70': 'Heavy rain and sleet',
		'71': 'Light rain and ice pellets',
		'72': 'Moderate rain and ice pellets',
		'73': 'Heavy rain and ice pellets',
		'74': 'Light snow and sleet',
		'75': 'Moderate snow and sleet',
		'76': 'Heavy snow and sleet',
		'77': 'Light snow and ice pellets',
		'78': 'Moderate snow and ice pellets',
		'79': 'Heavy snow and ice pellets',
		'80': 'Light sleet and ice pellets',
		'81': 'Moderate sleet and ice pellets',
		'82': 'Heavy sleet and ice pellets',
		'83': 'Light rain and snow',
		'84': 'Moderate rain and snow',
		'85': 'Heavy rain and snow',
		'86': 'Light rain and sleet',
		'87': 'Moderate rain and sleet',
		'88': 'Heavy rain and sleet',
		'89': 'Light rain and ice pellets',
		'90': 'Moderate rain and ice pellets',
		'91': 'Heavy rain and ice pellets',
		'92': 'Light snow and sleet',
		'93': 'Moderate snow and sleet',
		'94': 'Heavy snow and sleet',
		'95': 'Light snow and ice pellets',
		'96': 'Moderate snow and ice pellets',
		'97': 'Heavy snow and ice pellets',
		'98': 'Light sleet and ice pellets',
		'99': 'Moderate sleet and ice pellets',
	},
];

// transform the weatherCodes object into an array of objects
// with the code as key and the description as value
export const weatherCodesArray = Object.entries(weatherCodes[0]).map(
	([key, value]) => ({ [key]: value }),
) as TWeatherCode;
